/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.*;
import Ve2D.Point1;
import Ve2D.Vatcan;
import Ve2D.chuyendong;
import Ve3d.HinhChop;
import Ve3d.HinhHop;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Forrm extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    private static int i = 0;

    public Forrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jpview2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jToaDo1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jpview1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        VE = new javax.swing.JButton();
        CHUYENDONG = new javax.swing.JButton();
        XOA = new javax.swing.JButton();
        JToaDo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(52, 152, 219));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jpview2.setBackground(new java.awt.Color(255, 153, 0));
        jpview2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpview2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpview2Layout = new javax.swing.GroupLayout(jpview2);
        jpview2.setLayout(jpview2Layout);
        jpview2Layout.setHorizontalGroup(
            jpview2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );
        jpview2Layout.setVerticalGroup(
            jpview2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jButton3.setBackground(new java.awt.Color(52, 152, 219));
        jButton3.setText("Vẽ Hình Hộp");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setText("Vẽ Hình Chóp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 255));
        jButton2.setText("Xóa Tất Cả");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(125, 125, 125))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jToaDo1.setBackground(new java.awt.Color(183, 183, 183));
        jToaDo1.setColumns(20);
        jToaDo1.setRows(5);
        jScrollPane2.setViewportView(jToaDo1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpview2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jpview2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Đồ họa 3D", jPanel1);

        jpview1.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout jpview1Layout = new javax.swing.GroupLayout(jpview1);
        jpview1.setLayout(jpview1Layout);
        jpview1Layout.setHorizontalGroup(
            jpview1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );
        jpview1Layout.setVerticalGroup(
            jpview1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        VE.setBackground(new java.awt.Color(52, 152, 219));
        VE.setText("Vẽ");
        VE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEActionPerformed(evt);
            }
        });

        CHUYENDONG.setBackground(new java.awt.Color(52, 152, 219));
        CHUYENDONG.setText("Chuyển động ");
        CHUYENDONG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHUYENDONGActionPerformed(evt);
            }
        });

        XOA.setBackground(new java.awt.Color(52, 152, 219));
        XOA.setText("Xóa");
        XOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XOAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(XOA, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CHUYENDONG, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VE, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(VE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(CHUYENDONG, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(XOA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        JToaDo.setBackground(new java.awt.Color(183, 183, 183));

        javax.swing.GroupLayout JToaDoLayout = new javax.swing.GroupLayout(JToaDo);
        JToaDo.setLayout(JToaDoLayout);
        JToaDoLayout.setHorizontalGroup(
            JToaDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JToaDoLayout.setVerticalGroup(
            JToaDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jpview1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JToaDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JToaDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpview1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Đồ họa 2D", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void VeO(Graphics g) {
        for (int i = 1; i <= 800; i += 15) {
            g.drawLine(i, 1, i, 800);
            g.setColor(Color.WHITE);

        }

        for (int i = 1; i <= 820; i += 15) {
            g.drawLine(1, i, 800, i);
            g.setColor(Color.WHITE);
        }
    }

    private void VEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEActionPerformed
        // TODO add your handling code here:
        Graphics g = jpview1.getGraphics();
        chuyendong cd = new chuyendong();
        cd.CD1(g, 1, this);
        
//        Vatcan vc = new Vatcan();
//        vc.vevatcan(g, new Point1(20,3), Color.BLACK);

    }//GEN-LAST:event_VEActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jToaDo1.setText("");
        Graphics P = jpview2.getGraphics();
        Graphics2D G = (Graphics2D) P;

        VeToaDo(P);
        /*   BufferedImage bf = new BufferedImage(850, 850,BufferedImage.TYPE_INT_ARGB);
        Graphics buf = bf.getGraphics();
        Graphics2D dx = (Graphics2D) buf;
        Graphics2D dy = (Graphics2D) buf;
        Graphics2D dz = (Graphics2D) buf;
        Graphics2D o = (Graphics2D) buf;
        dx.setStroke(new BasicStroke(3f));
        o.drawImage(bf,0,0,null);
        o.setColor(Color.blue);
        o.setColor(Color.blue);
        o.setColor(Color.blue);
        
        o.drawString("X", 765, 370);
        o.drawString("O", 410, 365);
        o.drawString("Z", 420, 20);
        o.drawString("Y", 250, 610);
        
       
          // Vẽ trục oz
        G.setColor(Color.BLACK);
        G.setStroke(new BasicStroke(3f));
        G.drawLine(400, 10 , 400, 150);
        G.drawLine(400,10,390,20);
        G.drawLine(400,10,410,20);
        G.drawString("Z", 420, 20);
        
         */
        i++;

        int x = NhapX("tọa độ x", -30, 30);
        int y = NhapX("tọa độ y", -30, 30);
        int z = NhapX("tọa độ z", -30, 30);
        int dai = NhapX("độ dài", 10, 40);
        int rong = NhapX("độ rộng", 10, 40);
        int cao = NhapX("độ cao", 10, 40);

        HinhHop hh = new HinhHop(dai, rong, cao);
        hh.VeHinh(G, x, y, z, this, i);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void CHUYENDONGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHUYENDONGActionPerformed
        // TODO add your handling code here:

        Graphics g = jpview2.getGraphics();
        jpview2.setDoubleBuffered(true);
        
        chuyendong cd = new chuyendong();
        cd.CD1(g, 160, this);

    }//GEN-LAST:event_CHUYENDONGActionPerformed

    private void XOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XOAActionPerformed
        // TODO add your handling code here:

        jpview1.repaint();
        //jpview1.repaint();

    }//GEN-LAST:event_XOAActionPerformed

    private void jpview2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpview2MouseClicked
        // TODO add your handling code here:
        Graphics g = jpview2.getGraphics();
        VeToaDo(g);

    }//GEN-LAST:event_jpview2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jToaDo1.setText("");
        Graphics P = jpview2.getGraphics();
        Graphics2D G = (Graphics2D) P;
        VeToaDo(P);
        i++;
        int x = NhapX("tọa độ x", -30, 30);
        int y = NhapX("tọa độ y", -30,30);
        int z = NhapX("tọa độ z", -30, 30);
        int dai = NhapX("độ dài", 10, 40);
        int rong = NhapX("độ rộng", 10, 40);
        int cao = NhapX("độ cao", 10, 40);

        HinhChop hh = new HinhChop(dai, rong, cao);
        hh.VeHinhC(G, x, y, z, this, i);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jpview2.repaint();
        i = 0;
        jToaDo1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Forrm().setVisible(true);

            }
        });
    }

    private int NhapX(String s, int x, int y) {
        boolean t;
        String k;
        int p = 0;
        do {

            t = true;
            k = JOptionPane.showInputDialog(rootPane, "Nhập " + s + " ");
            if (k.equalsIgnoreCase(" ")) {
                t = false;
                JOptionPane.showMessageDialog(rootPane, "Không được bỏ trống");
            }
            if (!LaSo(k)) {
                t = false;
                JOptionPane.showMessageDialog(rootPane, "Không được nhập chữ !. Vui lòng nhập số");
            } else {
                p = Integer.parseInt(k);
                if (p < x || p > y) {
                    t = false;
                    JOptionPane.showMessageDialog(rootPane, "Chỉ được nhập trong khoảng từ " + x + " đến " + y);
                } else {
                    return p;
                }
            }

        } while (t == false);

        return -1;
    }

    private boolean LaSo(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    void VeToaDo(Graphics g) {
        //   Graphics g = jpview2.getGraphics();
        Graphics2D dx = (Graphics2D) g;
        Graphics2D dy = (Graphics2D) g;
        Graphics2D dz = (Graphics2D) g;
        Graphics2D o = (Graphics2D) g;
        dx.setStroke(new BasicStroke(3f));

        // ve ox
        dx.drawLine(400, 350, 770, 350);
        dx.drawLine(770, 350, 760, 340);
        dx.drawLine(770, 350, 760, 360);

        // Vẽ trục oz
        dz.setStroke(new BasicStroke(3f));
        dz.drawLine(400, 10, 400, 350);
        dz.drawLine(400, 10, 390, 20);
        dz.drawLine(400, 10, 410, 20);
        // ve truc oy

        dy.setStroke(new BasicStroke(3f));
        dy.drawLine(400, 350, 150, 600);
        dy.drawLine(150, 600, 150, 585);
        dy.drawLine(150, 600, 165, 600);

        //đặt tên cho trục va set màu tên cho trục
        o.setColor(Color.blue);
        o.setColor(Color.blue);
        o.setColor(Color.blue);

        o.drawString("X", 765, 370);
        o.drawString("O", 410, 365);
        o.drawString("Z", 420, 20);
        o.drawString("Y", 250, 610);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CHUYENDONG;
    public javax.swing.JPanel JToaDo;
    private javax.swing.JButton VE;
    private javax.swing.JButton XOA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextArea jToaDo1;
    private javax.swing.JPanel jpview1;
    private javax.swing.JPanel jpview2;
    // End of variables declaration//GEN-END:variables
}
